### ISSUE TITLE
Feature Idea: Advanced Git Parsing

### ISSUE THREAD

**Issue by kevintraver** [moyiz/git-dev.nvim#2]
It would be useful to have advance git parsing.

Could possibly use [https://github.com/linrongbin16/giturlparser.lua](https://github.com/linrongbin16/giturlparser.lua)

This would allow for some neat features:

- Opening directly to a file:

`https://github.com/moyiz/git-dev.nvim/blob/5808fe220441a7ed70a2882d91912353337c6035/README.md`

- Opening up with a specific branch checked out:

`https://github.com/neovim/neovim/tree/release-0.9`

Happy to help with a PR.

Thanks for the awesome plugin!

**Comment by nabiu256** [comment]
I was just checking the repo to see if this was somehow possible. It'd be a great thing to add!

**Comment by moyiz** [comment]
It sounds like a great idea, thanks for the suggestion!

It could possibly imply future support for opening repositories and files directly from shell `nvim https://github.com/....` (this claim needs to be verified).

At this stage I prefer to not add "hard" dependencies to this project.

Notice that the URLs in the issue are vendor specific and not actual Git URIs (e.g. GitLab would have a `/-/` in the URL to separate repository from blob / tree references, Gitea / Forgejo / Codeberg use totally different format).

`giturlparser.lua` is not aware of the differences between different git hosting platforms and won't be able to extract refs and specific file paths from it (which makes sense, since these are not actually valid Git URIs). Implementing a complete vendor aware URL parser that should cover all of these nuances, but it would take some time.

A possible alternative for the moment could be to extend / replace `GitRef` object to support `file` field, which could instruct the `opener` function of a specific file in the repository to auto-open. For the first example, it could be something similar to `:GitDevOpen moyiz/git-dev.nvim '{ref="5808fe220441a7ed70a2882d91912353337c6035",file="README.md"}'`.
Pros: quick, control is the user hands. Con: No seamless "copy-paste" support for URLs from browser, which seem to miss the purpose of this suggestion.

I will try to play with the vendor aware URL parser, so I am leaving this issue open.
Feel free to jump in with thoughts / suggestions :slightly_smiling_face:

**Comment by kevintraver** [comment]
This is awesome! 🥳
