### ISSUE TITLE
Feature request: Open file in local repo if it exists

### ISSUE THREAD

**Issue by GordianDziwis** [moyiz/git-dev.nvim#5]
I am using this function in tridactyl to run git-dev directly from the browser:
```
command browse_repo composite get_current_url | js -p tri.excmds.exclaim("alacritty -e zsh -c \"vi -c \'GitDevOpen " + JS_ARG + "\'\"")
```

But now there are two different kinds of repos:
1. `ephemeral` ones for git-dev 
2. the `local` Repos I am working on

I do not want to just set the `repositories_dir` var to my `local` repos. (like you advised)

Could git-dev then use two repositories dirs one for caching and one for only for opening.

So that then `GitDevOpen foo` does the following:

1. Check if the repo already exists in the `local` folder
2a. If it exists: Open the file from `local`
2b. If it does not exist, do the shallow clone in `ephemeral`...

**Comment by moyiz** [comment]
Thanks for creating an issue.

You are right to not set `repositories_dir` to local projects. The main reason is to be safe with mistakes / bugs around repository deletion. Deletion occurs in two scenarios:
- `nvim` exits after a `GitDevOpen` without `ephemeral=false`.
- `GitDevCleanAll` is called. It deletes the `repositories_dir` itself (might be removed / changed in the future).
 
The plugin's main focus is to provide a self cleaning local view of remote repositories. It supports multiple branches / tags / commits views of the same repository by including the ref in the local clone directory name.

The motivation behind disabling `ephemeral` is to reduce opening time for frequently viewed repositories. Re-opening cached repositories will still "refresh" the existing directory and checkout the requested branch / tag. It might include an optional hard reset in the future to better reflect the remote repository.

With that said, supporting such feature raises few behavioral questions, among them:
- Should the same repository directories naming convention be assumed in the `local` repositories directory (e.g. `gitlab.com__gitlab-org__code-creation__repository-x-ray#0450ca922f2fcaff4e3331a0407de4c102d07afd`)?
- How to handle possible conflicts?
- How to handle locally changed files?

This behavior might be out of scope at the moment.

Unless I am missing something, it sounds like the behavior you describe can be achieved with public API for URL parsing (https://github.com/moyiz/git-dev.nvim/pull/8). Then you could determine the local repository path and selected file to open, but outside the plugin.

Perhaps you can try a workaround like this: 
- Add a global function / user command for a custom opening logic. i added it to `~/.config/nvim/init.lua` for the sake of this example.
```
-- Temporarily in init.lua
function MyRepositoryOpener(url)
  local git_dev = require "git-dev"
  local parsed_repo = git_dev.parse(url)
  local repo_name = parsed_repo.repo_url:match "([^/]+).git"
  local local_repo = vim.fn.expand "~/workspace/" .. repo_name
  if repo_name and vim.fn.isdirectory(local_repo) == 1 then
    git_dev.config.opener(
      local_repo,
      parsed_repo.repo_url,
      parsed_repo.selected_path
    )
  else
    git_dev.open(url)
  end
end
```
  It uses the plugin's parser and extracts the repository name from the repository URL, then check if it exists as a local directory in a predefined path. It will call the plugin's `opener` on it, otherwise it will call `GitDevOpen`.
- Update `browse_repo` to call it instead:
```
command browse_repo composite get_current_url | shellescape | js -p tri.excmds.exclaim("alacritty -e bash -c \"nvim -c \'=MyRepositoryOpener(\\\"" + JS_ARG + "\\\")\'\"")
```

**Comment by GordianDziwis** [comment]
Thanks a lot for your detailed answer, the function is exactly what I needed.
