### ISSUE TITLE
Bug: Parser fails with GitLab URL

### ISSUE THREAD

**Issue by GordianDziwis** [moyiz/git-dev.nvim#6]
The following URL fails: `https://gitlab.com/infai/rdf-diagram-framework/-/blob/typeScriptRewrite/rdf-diagram-drawio/src/plugins/rdf-diagram.ts`

**Comment by moyiz** [comment]
Thanks for reporting!
This bug seem to happen due to the default clone arguments and the fact that branch name was not passed to the clone command. The default arguments contain `--single-branch` which will cause the later `checkout` to fail. Removing it can workaround this issue. A better fix is to clone a single but correct branch with `-b`, and will be merged soon.
